services:
  php:
    build:
      dockerfile: ./php/Dockerfile
    container_name: twb_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: twb_nginx
    ports:
      - "8086:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:latest
    container_name: twb_db
    environment:
      MYSQL_DATABASE: twb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: twb_phpMyAdmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8089:80"
    depends_on:
      - db
    platform: linux/amd64

volumes:
  mysql_data:
